#!/usr/bin/env bun
import { createHash, randomUUID } from "node:crypto";
import { lstat, mkdir, mkdtemp, open, readFile, readdir, realpath, rename, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { parseArgs } from "node:util";
import { linkPlugins } from "./link-codex-plugins";

const marker = "# Generated by agent-plugins/scripts/sync-codex.ts. DO NOT EDIT.";
const roles = [
  ["ship-check", "pr-reviewer"],
  ["ship-check", "code-quality-reviewer"],
  ["ship-check", "test-auditor"],
  ["ship-check", "bug-checker"],
  ["plan-check", "plan-reviewer"],
] as const;
const builtinTools = new Map([
  ["Read", "read files"], ["Edit", "edit files"], ["Write", "write files"],
  ["Bash", "execute shell commands"], ["Grep", "search text"],
  ["Glob", "find paths"], ["ToolSearch", "discover tools"],
]);
const vaultOperations = new Set([
  "vault_get_memory", "vault_read_note", "vault_read_file", "vault_memory_recall",
  "vault_list_memory_files", "vault_search", "vault_search_by_folder", "vault_search_by_property",
  "vault_search_by_tag", "vault_list_notes", "vault_list_files", "vault_list_tags",
  "vault_list_property_keys", "vault_list_property_values", "vault_list_tasks",
  "vault_get_backlinks", "vault_get_outgoing_links", "vault_get_daily_note", "vault_recent_notes", "vault_find_orphans",
]);
const allowedFields = new Set(["name", "description", "model", "color", "tools", "skills"]);
// Names must remain a single path component; qualified skills can select either bundled plugin.
const skillNamePattern = /^(?:(ship-check|plan-check):)?([a-z0-9]+(?:-[a-z0-9]+)*)$/;
// Only the leading YAML document is metadata; the body is embedded without rewriting it.
const frontmatterPattern = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/;

type SyncOptions = { repoRoot: string; codexHome: string; skillRoot: string; check?: boolean; linkPlugins?: boolean };
type SyncResult = { current: boolean; changed: number; linksChanged: number; backupDirectory?: string };
type Output = { path: string; name: string; content: string; original: string | undefined };
type Source = { path: string; content: string };

const isMissing = (error: unknown) => error instanceof Error && "code" in error && error.code === "ENOENT";
const sha256 = (content: string) => createHash("sha256").update(content).digest("hex");
const readOptional = async (path: string) => {
  try { return await readFile(path, "utf8"); }
  catch (error) { if (isMissing(error)) return; throw error; }
};
const statOptional = async (path: string) => {
  try { return await lstat(path); }
  catch (error) { if (isMissing(error)) return; throw error; }
};
const validateDirectory = async (path: string) => {
  const stat = await statOptional(path);
  if (stat && (!stat.isDirectory() || stat.isSymbolicLink())) throw new Error(`Expected a real directory: ${path}`);
};
const knownTool = (name: string) => {
  if (builtinTools.has(name) || name === "mcp__sequential-thinking__sequentialthinking") return true;
  return ["mcp__claude_ai_Vault_Cortex__", "mcp__vault-cortex__"].some(prefix => name.startsWith(prefix) && vaultOperations.has(name.slice(prefix.length)));
};
const stringArray = (value: unknown): value is string[] => Array.isArray(value) && value.every(item => typeof item === "string" && Boolean(item));
const splitNote = (source: Source) => {
  const match = frontmatterPattern.exec(source.content);
  if (!match) throw new Error(`Missing YAML frontmatter: ${source.path}`);
  const properties: unknown = Bun.YAML.parse(match[1]);
  if (!properties || typeof properties !== "object" || Array.isArray(properties)) throw new Error(`Invalid YAML frontmatter: ${source.path}`);
  return { properties, body: source.content.slice(match[0].length) };
};

const buildPlan = async (options: SyncOptions) => {
  const agentDirectory = join(options.codexHome, "agents");
  await validateDirectory(agentDirectory);
  await validateDirectory(join(options.codexHome, "agent-sync-backups"));
  const sources: Source[] = [];
  const outputs: Output[] = [];
  const load = async (path: string) => {
    const content = await readOptional(path);
    if (content === undefined) throw new Error(`Missing required source: ${path}`);
    const source = { path, content };
    sources.push(source);
    return source;
  };
  for (const [plugin, role] of roles) {
    const source = await load(join(options.repoRoot, "plugins", plugin, "agents", `${role}.md`));
    const { properties, body } = splitNote(source);
    const unknown = Object.keys(properties).filter(key => !allowedFields.has(key));
    if (unknown.length) throw new Error(`Unsupported agent fields in ${source.path}: ${unknown.join(", ")}`);
    if (!("name" in properties) || properties.name !== role || !("description" in properties) || typeof properties.description !== "string" || !properties.description.trim()) throw new Error(`Invalid agent name or description: ${source.path}`);
    if (!("model" in properties) || properties.model !== "inherit") throw new Error(`Agent model must be inherit: ${source.path}`);
    if ("color" in properties && typeof properties.color !== "string") throw new Error(`Agent color must be a string: ${source.path}`);
    if (!("tools" in properties) || !stringArray(properties.tools) || !properties.tools.every(knownTool)) throw new Error(`Unsupported or missing agent tools: ${source.path}`);
    if (!("skills" in properties) || !stringArray(properties.skills) || !properties.skills.length) throw new Error(`Missing or invalid agent skills: ${source.path}`);
    const roleSources = [source];
    const permittedOperations = [...new Set(properties.tools.map(tool => builtinTools.get(tool) ?? tool.split("__").at(-1) ?? tool))];
    const instructions = [
      "These are shared Claude-source role instructions and preloaded skill bodies for a native Codex agent. Claude tool names describe operations; use the available Codex equivalents. Actual tools, MCP connections, permissions, model, and reasoning effort inherit from the parent. Claude builtin tool allowlists cannot be represented faithfully here and are not enforced by native configuration.",
      `Source-declared permitted operations: ${permittedOperations.join(", ")}. Treat this list as an instruction-level constraint; do not use other operations just because inherited tools expose them.`,
      ...(plugin === "plan-check" ? ["The plan reviewer defaults to the native read-only filesystem sandbox. Parent live policy may override this default; filesystem sandboxing does not restrict remote MCP writes."] : []),
      `## Agent source: ${source.path}\n${body}`,
    ];
    for (const skill of properties.skills) {
      const match = skillNamePattern.exec(skill);
      if (!match) throw new Error(`Unsupported skill reference ${skill}: ${source.path}`);
      const bundled = join(options.repoRoot, "plugins", match[1] ?? plugin, "skills", match[2], "SKILL.md");
      const useBundled = Boolean(match[1]) || Boolean(await statOptional(bundled));
      const skillPath = useBundled ? bundled : join(options.skillRoot, match[2], "SKILL.md");
      const skillSource = await load(skillPath);
      const skillNote = splitNote(skillSource);
      roleSources.push(skillSource);
      instructions.push(`## Preloaded skill: ${skill}\nSource: ${skillPath}\n${skillNote.body}`);
    }
    const name = `${plugin}-${role}.toml`;
    const path = join(agentDirectory, name);
    const stat = await statOptional(path);
    if (stat && (!stat.isFile() || stat.isSymbolicLink())) throw new Error(`Refusing non-regular output: ${path}`);
    const original = await readOptional(path);
    if (original !== undefined && !original.startsWith(`${marker}\n`)) throw new Error(`Refusing to replace an unowned agent file: ${path}`);
    const content = [
      marker,
      ...roleSources.map(item => `# Source ${JSON.stringify(item.path)} sha256=${sha256(item.content)}`),
      `name = ${JSON.stringify(`${plugin}:${role}`)}`,
      `description = ${JSON.stringify(properties.description)}`,
      ...(plugin === "plan-check" ? ['sandbox_mode = "read-only"'] : []),
      `developer_instructions = ${JSON.stringify(instructions.join("\n\n"))}`,
      "",
    ].join("\n");
    outputs.push({ path, name, content, original });
  }
  for (const name of await readdir(agentDirectory).catch(error => { if (isMissing(error)) return []; throw error; })) {
    if (!name.endsWith(".toml") || outputs.some(output => output.name === name)) continue;
    const path = join(agentDirectory, name);
    const stat = await lstat(path);
    if (stat.isFile() && (await readFile(path, "utf8")).startsWith(`${marker}\n`)) {
      throw new Error(`Obsolete generated agent: ${path}. Move it outside the agents directory, then rerun sync.`);
    }
  }
  const links = options.linkPlugins ? await linkPlugins({ ...options, check: true }) : { current: true };
  return { sources, outputs, linksCurrent: links.current };
};

const validateOriginal = async (output: Output) => {
  const stat = await statOptional(output.path);
  if ((stat && (!stat.isFile() || stat.isSymbolicLink())) || await readOptional(output.path) !== output.original) {
    throw new Error(`Agent changed during sync; rerun after checking it: ${output.path}`);
  }
};

export const syncCodex = async (input: SyncOptions): Promise<SyncResult> => {
  const options = { ...input, repoRoot: await realpath(resolve(input.repoRoot)), codexHome: await realpath(resolve(input.codexHome)), skillRoot: resolve(input.skillRoot) };
  if (dirname(options.codexHome) === options.codexHome) throw new Error("Refusing a filesystem root as Codex home.");
  if (options.check) {
    const plan = await buildPlan(options);
    return { current: plan.linksCurrent && plan.outputs.every(output => output.content === output.original), changed: 0, linksChanged: 0 };
  }
  const lockPath = join(options.codexHome, ".agent-plugins-sync.lock");
  const lockContent = JSON.stringify({ pid: process.pid, token: randomUUID() });
  const lock = await open(lockPath, "wx", 0o600).catch(error => {
    if (error instanceof Error && "code" in error && error.code === "EEXIST") throw new Error(`Sync lock exists: ${lockPath}. Read its PID, verify that process has stopped, then remove the stale lock manually; active runs must finish first.`);
    throw error;
  });
  const stagingDirectories = new Set<string>();
  try {
    await lock.writeFile(lockContent);
    const plan = await buildPlan(options);
    const changed = plan.outputs.filter(output => output.content !== output.original);
    if (!changed.length && plan.linksCurrent) return { current: true, changed: 0, linksChanged: 0 };
    const stage = await mkdtemp(join(options.codexHome, ".agent-sync-stage-"));
    stagingDirectories.add(stage);
    for (const output of changed) await writeFile(join(stage, output.name), output.content, { mode: 0o600 });
    for (const source of plan.sources) {
      if (await readOptional(source.path) !== source.content) throw new Error(`Source changed during sync; rerun: ${source.path}`);
    }
    for (const output of plan.outputs) await validateOriginal(output);
    await validateDirectory(join(options.codexHome, "agents"));
    const originals = changed.filter(output => output.original !== undefined);
    const backupRoot = join(options.codexHome, "agent-sync-backups");
    await validateDirectory(backupRoot);
    if (originals.length) await mkdir(backupRoot, { recursive: true, mode: 0o700 });
    const backupDirectory = originals.length ? await mkdtemp(join(backupRoot, "sync-")) : undefined;
    if (backupDirectory) {
      for (const output of originals) {
        if (output.original !== undefined) await writeFile(join(backupDirectory, output.name), output.original, { mode: 0o600 });
      }
    }
    if (changed.length) await mkdir(join(options.codexHome, "agents"), { recursive: true, mode: 0o700 });
    for (const output of changed) {
      await validateDirectory(join(options.codexHome, "agents"));
      await validateOriginal(output);
      await rename(join(stage, output.name), output.path);
    }
    const links = options.linkPlugins ? await linkPlugins(options) : { changed: 0 };
    return { current: true, changed: changed.length, linksChanged: links.changed, backupDirectory };
  } finally {
    try {
      await lock.close();
      for (const stage of stagingDirectories) await rm(stage, { recursive: true, force: true });
    } finally {
      if (await readOptional(lockPath) === lockContent) await rm(lockPath);
    }
  }
};

if (import.meta.main) {
  try {
    const { values } = parseArgs({ options: {
      check: { type: "boolean", default: false },
      "link-plugins": { type: "boolean", default: false },
      "repo-root": { type: "string" }, "codex-home": { type: "string" }, "skill-root": { type: "string" },
      help: { type: "boolean", default: false },
    } });
    if (values.help) {
      console.log("Usage: bun scripts/sync-codex.ts [--check] [--link-plugins] [--repo-root PATH] [--codex-home PATH] [--skill-root PATH]\nGenerates five native Codex agents from shared role and skill sources. --check never writes. --link-plugins also links the two already-installed plugin caches. Model, effort, tools and MCP configuration inherit; Claude allowlists become instruction-level constraints, not native enforcement. Plan review defaults to a read-only filesystem sandbox; parent live policy may override it. Originals are retained under CODEX_HOME/agent-sync-backups; rerun after interruption to finish owned outputs. Each file is replaced atomically, not the whole set. Re-run after source/skill changes, and restart Codex to reload agents.");
    } else {
      const result = await syncCodex({ repoRoot: values["repo-root"] ?? resolve(import.meta.dir, ".."), codexHome: values["codex-home"] ?? process.env.CODEX_HOME ?? join(homedir(), ".codex"), skillRoot: values["skill-root"] ?? join(homedir(), ".agents/skills"), check: values.check, linkPlugins: values["link-plugins"] });
      console.log(result.current ? `Codex sync current (${result.changed} agents, ${result.linksChanged} links changed).` : "Codex sync stale; rerun without --check.");
      if (result.backupDirectory) console.log(`Original agents: ${result.backupDirectory}`);
      process.exitCode = result.current ? 0 : 1;
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
